services:
#  fastapi:
#    build: ./fastapi
#    ports:
#      - "8000:8000"
#    environment:
#      - MODEL_PATH=/models
#      - CUDA_VISIBLE_DEVICES=0
#    volumes:
#      - ./models:/models
#    deploy:
#      resources:
#        reservations:
#          devices:
#            - driver: nvidia
#              count: 1
#              capabilities: [ gpu ]


  postgresql:
    image: postgres:15
    container_name: alaw-postgres
    volumes:
      - ./postgres/conf:/etc/postgresql/conf.d   # 필요 시 설정 파일 마운트
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d  # 초기 SQL 스크립트(선택)
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  # MongoDB
  mongo:
      image: mongo:6.0
      container_name: alaw-mongo
      ports:
      - '27017:27017'
      volumes:
      - ./mongo/data:/data/db
      environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}

  # Redis
  redis:
    image: redis:7.2.5
    container_name: alaw-redis
    ports:
      - '6379:6379'
#  rabbitmq:
#    image: rabbitmq:3.11-management
#    container_name: alaw-rabbitmq
#    restart: unless-stopped
#    ports:
#      - "5672:5672"    # AMQP
#      - "15672:15672"  # Management UI
#    environment:
#      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
#      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
#    volumes:
#      - ./rabbitmq/data:/var/lib/rabbitmq
#      - ./rabbitmq/log:/var/log/rabbitmq
#      - ./rabbitmq/conf:/etc/rabbitmq  # 필요 시 설정 파일 마운트
#    healthcheck:
#      test: ["CMD", "rabbitmqctl", "status"]
#      interval: 30s
#      timeout: 10s
#      retries: 5


networks:
  backend:
    driver: bridge
